Typescript
karolinachodera/shopping-list pull request #3
Opened 2023-03-28 13:04 UTC by karolinachodera

2023-03-31 19:11 UTC, biern-j requested changes
Nice work :) I hope this exercise helps you lear TypeScript.
We can talk about my comments on the next meeting.

2023-03-31 19:11 UTC, biern-j commented on script.ts
> +function startItem(this: HTMLFormElement, e: Event): void {
Great! I also found an article with an explanation of how to add types to 'this'  [here](https://betterprogramming.pub/introduction-to-typescript-functions-this-object-and-overloads-6d03a90f1821).

2023-03-31 19:11 UTC, biern-j commented on script.ts
> +function moveToEnd(this: HTMLElement, e: Event): void{
```suggestion
function moveToEnd(this: HTMLElement, e: Event): void {
```

2023-03-31 19:11 UTC, biern-j commented on tsconfig.json
> +}
Do you need these commanded config rules? I get would rid of them.

2023-03-31 19:11 UTC, biern-j commented on node_modules/typescript/package.json
Please add the 'node_modules' folder to .gitignore.
I recommend reading [this article](https://www.freecodecamp.org/news/gitignore-file-how-to-ignore-files-and-folders-in-git/#contents) to get to know what kind of files and folders we should put into the .gitignore file.

2023-03-31 19:11 UTC, biern-j commented on node_modules/typescript/package.json
When you will make this correction you will have to remove node_modules from git.
With this command you will delete node_modules from git and clear cached git history:
`$ git rm --cached .node_modules`

2023-03-31 19:11 UTC, biern-j commented on script.ts
> +}
I would pass the types directly into the class. 

```suggestion
class ItemObject {
    name: string;
    category: string;
    id: number;
    isChecked: boolean;
    constructor (name: string, category: string) {
        this.name = name;
        this.category = category;
        this.id = index;
        this.isChecked = false;
    }
}
```

2023-04-04 19:26 UTC, biern-j commented on .gitignore
> +node_modules/
This red icon means that you have an empty line at the end of the code. You can delete it ;)

2023-04-05 08:40 UTC, karolinachodera commented on script.ts
> +}
I'm not sure if I combine these parts of the code, will I still have type/interface "ItemObject" defined? Or maybe defining an interface is not needed when using a class?

2023-04-13 08:43 UTC, biern-j approved these changes

2023-04-13 09:05 UTC, merged